name: Trigger Birthday Script

on:
  schedule:
    # Every 5 minutes
    - cron: "*/5 * * * *"

  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install

      - run: npx playwright install --with-deps chromium

      - run: node trigger.js
